added a way to connect to consul KV
rawmind0/alpine-traefik pull request #93
Opened 2018-03-28 08:56 UTC by volatilemolotov12

Hello, 

I have added simple consul config parameteres. I have tested this and it connects successfully . This does not interfere with other configs as i have both rancher api integration and consul as config backends.

2018-04-13 09:59 UTC, rawmind0 requested changes

2018-04-13 09:59 UTC, rawmind0 commented on root/opt/traefik/bin/traefik.toml.sh
> +"
As consult backend support constraints, https://docs.traefik.io/configuration/commons/#backend-specific, that are already implemented on image, could you please add constraint support??
```
+
+    if [ "${TRAEFIK_CONSTRAINTS}" != "" ]; then
+        TRAEFIK_CONSUL_CFG=${TRAEFIK_CONSUL_CFG}"\
+  constraints = [ ${TRAEFIK_CONSTRAINTS} ]
+"
+    fi
+
```

2018-04-13 10:02 UTC, rawmind0 commented
Hi @volatilemolotov12 . Thanks for the PR and contribute.

Please, take a look at changes requested to add support to contraints. Also could you please include in PR, README.md update with new env vars??

2018-06-02 03:28 UTC, jonahlau commented
Are there any updates on this PR?

2023-10-31 12:34 UTC, closed without merging